### ISSUE TITLE
identify genetic clusters using diffrent inputs

### ISSUE THREAD

**Issue by elina2410** [insapathogenomics/ReporTree#23]
Hi,
I performed cgMLST analysis using chewBBACA. In the tutorial (https://chewbbaca.readthedocs.io/en/latest/user/modules/AlleleCall.html) they recommend to use the allelic profiles contained in the results_alleles.tsv output file after AllelCalling step. But using this file, the results of clustering are not congruent with MSTree and distance matrix (obtained by performing ExtractCgMLST, and using Grapetree for MST and distance matrix creation). When I use cgMLST.tsv file (results_alleles.tsv after ExtractCgMLST) as an input for Reportree (analysis Grapetree, method MSTreeV2), results are congruent. I know that after ExtractCgMLST process on results_alleles.tsv the output file -cgMLST.tsv no longer contains LNF, ASM etc, only 0 and other numbers. I am confused which file to use?
Best,
E

**Comment by vmixao** [comment]
Hi @elina2410 ,

Thanks for your interest in ReporTree.

I am not sure about what you mean with congruent because I did not understand what you are comparing. Are you comparing the results you obtain with the allele matrices before and after chewBBACA ExtractCgMLST, using in both cases the same clustering method (MSTreeV2)? If so, clustering is not congruent because before ExtractCgMLST the loci without an allele called are indicated with different codes (LNF, ASM, etc.) and being interpreted by ReporTree as an allele, while after ExtractCgMLST these codes are replaced by 0 and being interpreted as missing data. So, you should always use the one you obtained with ExtractCgMLST in which these loci appear as 0 (missing data). If you do not want to lose loci during chewBBACA ExtractCgMLST, you can set --t 0.

Please let me know if this answers your question.

Thanks.

Best,
Verónica

**Comment by elina2410** [comment]
Hi @vmixao ,
I use Reportree in order to define clusters at a set threshold eg. 5 allelic differences. I could do  this by viewing MST here https://achtman-lab.github.io/GrapeTree/MSTree_holder.html and then set "Branch Style/Collapse Branches: 5" or based on matrix distance. But I wanted to do it in more 'automated way' especially when I need to analyse many strains.  And I inspected if results from Reportree gives me the same cluster composition, at defined thresholds, as above mentioned "manual" methods.
And yes, you explained my doubts. 
Thank you.
E
