### ISSUE TITLE
https://achtman-lab.github.io/maketree throws 405 error

### ISSUE THREAD

**Issue by jhc9-cdc** [insapathogenomics/ReporTree#27]
In testing the referenced achtman-lab instance of grapetree, I am getting a 405 error trying to initiate a grapetree session (https://achtman-lab.github.io/maketree) and failed to load resource. Thus, when I try to load a SNP distance tsv file, it says it Cannot Connect to the backend server. It doesn't have this issue when I load the local install of the win version.  What do you recommend to resolve this configuration issue?

**Comment by vmixao** [comment]
Hi @jhc9-cdc 

If I understand correctly, this issue is not related to ReporTree but with Grapetree, right? 

I don’t know how to help you solving the issue, but **have you tried ReporTree**? You can provide your allele/SNP matrix to ReporTree and it will generate the MSTree/MSTreeV2 tree for you. You can do this in the command line (taking advantage of all ReporTree’s features) or opening Grapetree’s interactive visualization through ReporTree’s conda environment or docker image.

Also, you mention that **you are providing the SNP distance tsv to GrapeTree**. However, if I am not mistaken, **GrapeTree does not accept distance matrices** as input. You need to provide the SNP matrix or the tree already created (e.g. through ReporTree). If you are providing a distance matrix in your win installation, you are getting a tree but probably a wrong one because GrapeTree interprets it as a profile.

If you need any help with ReporTree, do not hesitate in contacting us.

Kind regards,
Verónica
